### ISSUE TITLE
 fail to POST driver for large objects

### ISSUE THREAD

**Issue by shayansaeed93** [intel-cloud/cosbench#187]
I am trying to benchmark my ceph librados. If I provide a workload of 4M objects, it passes but for workload of 128M, it always fails in the prepare stage with the driver crashing. I have tried changing the number of objects in prepare stage as well as the number of workers. 
This is my system.log for the workload 

2014-07-02 11:58:22,641 [INFO] [WorkloadProcessor] - begin to process workload w12 
2014-07-02 11:58:22,642 [INFO] [WorkloadProcessor] - begin to run stage s1-init 
2014-07-02 11:58:22,642 [INFO] [WorkloadProcessor] - ============================================ 
2014-07-02 11:58:22,642 [INFO] [WorkloadProcessor] - START WORK: init 
2014-07-02 11:58:22,692 [INFO] [AbstractCommandTasklet] - time drift between controller and driver-driver1 is 36 mSec 
2014-07-02 11:58:22,692 [INFO] [StageRunner] - successfully booted all tasks in stage s1-init 
2014-07-02 11:58:22,927 [INFO] [StageRunner] - successfully submitted all tasks in stage s1-init 
2014-07-02 11:58:22,937 [INFO] [StageRunner] - successfully authenticated all tasks in stage s1-init 
2014-07-02 11:58:23,143 [INFO] [StageRunner] - successfully launched all tasks in stage s1-init 
2014-07-02 11:58:28,155 [INFO] [StageRunner] - successfully queried all tasks in stage s1-init 
2014-07-02 11:58:28,227 [INFO] [StageRunner] - successfully closed all tasks in stage s1-init 
2014-07-02 11:58:28,228 [INFO] [StageRunner] - acceptable failure ratio of work s1-init-init = 0.0 
2014-07-02 11:58:28,228 [INFO] [StageRunner] - real failure ratio of work s1-init-init = N/A 
2014-07-02 11:58:28,228 [INFO] [StageRunner] - successfully reach the goal of acceptable failure ratio in stage s1-init - work init 
2014-07-02 11:58:30,644 [INFO] [WorkloadProcessor] - END WORK:   init, Time elapsed: 0:0::8 
2014-07-02 11:58:30,644 [INFO] [WorkloadProcessor] - ============================================ 
2014-07-02 11:58:30,644 [INFO] [WorkloadProcessor] - 
2014-07-02 11:58:30,644 [INFO] [WorkloadProcessor] - successfully ran stage s1-init 
2014-07-02 11:58:30,645 [INFO] [WorkloadProcessor] - begin to run stage s2-prepare 
2014-07-02 11:58:30,645 [INFO] [WorkloadProcessor] - ============================================ 
2014-07-02 11:58:30,645 [INFO] [WorkloadProcessor] - START WORK: prepare 
2014-07-02 11:58:30,651 [INFO] [AbstractCommandTasklet] - time drift between controller and driver-driver1 is 1 mSec 
2014-07-02 11:58:30,652 [INFO] [StageRunner] - successfully booted all tasks in stage s2-prepare 
2014-07-02 11:58:30,684 [INFO] [StageRunner] - successfully submitted all tasks in stage s2-prepare 
2014-07-02 11:58:30,688 [INFO] [StageRunner] - successfully authenticated all tasks in stage s2-prepare 
2014-07-02 11:58:30,892 [INFO] [StageRunner] - successfully launched all tasks in stage s2-prepare 
2014-07-02 11:58:38,025 [ERROR] [AbstractHttpTasklet] - fail to POST driver 
java.net.SocketException: Connection reset 
        at java.net.SocketInputStream.read(SocketInputStream.java:196) 
        at java.net.SocketInputStream.read(SocketInputStream.java:122) 
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149) 
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:111) 
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:264) 
        at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:98) 
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252) 
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:282) 
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247) 
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:216) 
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298) 
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) 
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:647) 
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:464) 
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820) 
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754) 
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732) 
        at com.intel.cosbench.controller.tasklet.AbstractHttpTasklet.issueHttpRequest(AbstractHttpTasklet.java:60) 
        at com.intel.cosbench.controller.tasklet.AbstractCommandTasklet.issueCommand(AbstractCommandTasklet.java:71) 
        at com.intel.cosbench.controller.tasklet.Querier.execute(Querier.java:48) 
        at com.intel.cosbench.controller.tasklet.AbstractTasklet.call(AbstractTasklet.java:47) 
        at com.intel.cosbench.controller.tasklet.AbstractTasklet.call(AbstractTasklet.java:1) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
        at java.lang.Thread.run(Thread.java:744) 
2014-07-02 11:58:38,025 [WARN] [Querier] - some unexpected exception occurs when ping drivers, but it's ignorable. 
com.intel.cosbench.controller.tasklet.TaskletException 
        at com.intel.cosbench.controller.tasklet.AbstractHttpTasklet.issueHttpRequest(AbstractHttpTasklet.java:72) 
        at com.intel.cosbench.controller.tasklet.AbstractCommandTasklet.issueCommand(AbstractCommandTasklet.java:71) 
        at com.intel.cosbench.controller.tasklet.Querier.execute(Querier.java:48) 
        at com.intel.cosbench.controller.tasklet.AbstractTasklet.call(AbstractTasklet.java:47) 
        at com.intel.cosbench.controller.tasklet.AbstractTasklet.call(AbstractTasklet.java:1) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
        at java.lang.Thread.run(Thread.java:744) 

This is my configuration.xml 

  GNU nano 2.2.6                                              File: myconf/ceph1                                                                                                   

<?xml version="1.0" encoding="UTF-8" ?> 
<workload name="128M" description="sample benchmark for librados">

  <storage type="librados" config="accesskey=admin;secretkey=AQDzSatTULP8DhAASLV3XOOWHVgKy3vwio03iw==;endpoint=sds-s2" />

  <workflow>

    <workstage name="init">
      <work type="init" workers="1" config="containers=r(1,2)" />
    </workstage>

    <workstage name="prepare">
      <work type="prepare" workers="1" config="containers=r(1,2);objects=r(1,5);sizes=c(128)MB" />
    </workstage>

    <workstage name="main">
      <work name="main" workers="8" runtime="1000">
        <operation type="read" ratio="50" config="containers=u(1,2);objects=u(1,5)" />
        <operation type="write" ratio="50" config="containers=u(1,2);objects=u(6,10);sizes=c(128)MB" />
      </work>
    </workstage>

    <workstage name="cleanup">
      <work type="cleanup" workers="1" config="containers=r(1,2);objects=r(1,10)" />
    </workstage>

    <workstage name="dispose">
      <work type="dispose" workers="1" config="containers=r(1,2)" />
    </workstage>

  </workflow>

</workload>

**Comment by ywang19** [comment]
we recently identified and resolved this issue, pls try the latest v0.4.2.c1 release.
