### ISSUE TITLE
Working with Ceph 0.87 encountered errors

### ISSUE THREAD

**Issue by ywang19** [intel-cloud/cosbench#238]
One user tried to test Ceph Giant (0.87) through librados adapter, and received exceptions:

2015-01-20 11:14:14,796 [ERROR] [AbstractCommandHandler] - unexpected error
com.intel.cosbench.api.storage.StorageException: com.ceph.rados.RadosException: The connection to the Ceph cluster failed (-95)
	at com.intel.cosbench.api.librados.LibradosStorage.init(LibradosStorage.java:75)
	at com.intel.cosbench.driver.service.COSBStorageAPIService.getStorage(COSBStorageAPIService.java:54)
	at com.intel.cosbench.driver.service.MissionHandler.createStorageApi(MissionHandler.java:210)
	at com.intel.cosbench.driver.service.MissionHandler.createWorkerContext(MissionHandler.java:197)
	at com.intel.cosbench.driver.service.MissionHandler.createWorkers(MissionHandler.java:185)
	at com.intel.cosbench.driver.service.MissionHandler.init(MissionHandler.java:100)
	at com.intel.cosbench.driver.service.COSBDriverService.createHandler(COSBDriverService.java:111)
	at com.intel.cosbench.driver.service.COSBDriverService.submit(COSBDriverService.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by ywang19** [comment]
rados-java library needs update.
