### ISSUE TITLE
unable to run workload against HP public cloud

### ISSUE THREAD

**Issue by gonewest818** [intel-cloud/cosbench#278]
Using 0.4.2.c2, I'm trying to define and run a workload against the HP public cloud implementation of swift.  So far all my attempts to modify the config are failing, and frankly there isn't enough information in the logs to help pinpoint further.

What I can see.  The workload-log.txt include a stack trace as follows:
```
================================================== stage: s1-init ==================================================
---------------------------------- mission: MA40AD97CB3, driver: cosbench_driver.263528a8-1e90-11e5-aabf-fa163e055b81 ----------------------------------
2015-06-29 18:56:34,959 [INFO] [Log4jLogManager] - will append log to file /home/cosbench/0.4.2.c2/log/mission/MA40AD97CB3.log
2015-06-29 18:56:35,461 [INFO] [NoneStorage] - performing PUT at /mycontainers1
2015-06-29 18:56:35,470 [ERROR] [AbstractOperator] - worker 1 fail to perform operation mycontainers1
com.intel.cosbench.api.storage.StorageException: java.lang.IllegalStateException: Target host must not be null, or set in parameters.
	at com.intel.cosbench.api.swift.SwiftStorage.createContainer(SwiftStorage.java:188)
	at com.intel.cosbench.driver.operator.Preparer.doInit(Preparer.java:113)
	at com.intel.cosbench.driver.operator.Preparer.operate(Preparer.java:87)
	at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
	at com.intel.cosbench.driver.operator.Initializer.operate(Initializer.java:1)
	at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
	at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
	at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Target host must not be null, or set in parameters.
	at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:719)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:358)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.intel.cosbench.client.swift.SwiftClient.getContainerInfo(SwiftClient.java:104)
	at com.intel.cosbench.client.swift.SwiftClient.containerExists(SwiftClient.java:343)
	at com.intel.cosbench.api.swift.SwiftStorage.createContainer(SwiftStorage.java:176)
	... 13 more
================================================== stage: s2-prepare ==================================================
================================================== stage: s3-normal ==================================================
================================================== stage: s4-cleanup ==================================================
================================================== stage: s5-dispose ==================================================
```

The relevant piece of the workload configuration is here:
```
       <workstage name="init" closuredelay="0" config="">
            <auth type="keystone" config="username=XXXXX;password=XXXXX;tenant_name=XXXXX;url=https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/;service=swift"/>
            <storage type="swift" config=""/>
            <work name="init" type="init" workers="1" interval="5"
                division="container" runtime="0" rampup="0" rampdown="0"
                afr="0" totalOps="1" totalBytes="0" config="containers=r(1,4)">
```

I can hazard a guess that the driver is unable to parse the service catalog returned by HP Helion OpenStack (http://docs.hpcloud.com/publiccloud/api/v2identity/#authenticate) either due to multiple regions or multiple swift endpoints in a given region, something along those lines.

If anyone happens to know the proper keystone config for HP cloud, I would appreciate a note back.  Alternately, if there is some way to get more descriptive logging that would be a step forward too.

**Comment by ywang19** [comment]
The exception means COSBench couldn’t get correct storage url, could you paste the json output for a successful keystone authentication?

-yaguang

**Comment by gonewest818** [comment]
Here it is.  

Note, I did a global search and replace of my username, tenant name, tenant id, the token id, and so on.  But the structure is unchanged. 

I saw below that the swift service is named "Object Storage" with type "object-store" so I tried both of those strings in the <auth type="keystone" config="...;service=object-store"> in the workload definition, but that doesn't solve my problem.

```
% curl -X POST https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/tokens -d @cred2.json  -H "Content-Type: application/json"
{"access": {
  "token": {
    "expires": "2015-06-30T13:55:10.453Z",
    "id": "<the-token>",
    "tenant": {
      "id": "<my-tenant-id>",
      "name": "<my-tenant-name>"
    }
  },
  "user": {
    "id": "<my-id>",
    "name": "<my-user-name>",
    "otherAttributes": {
      "domainStatus": "enabled",
      "domainStatusCode": "00"
    },
    "roles": [
    // ... deleted
    ]
  },
  "serviceCatalog": [
    {
      "name": "Identity",
      "type": "identity",
      "endpoints": [
        {
          "publicURL": "https:\/\/region-a.geo-1.identity.hpcloudsvc.com:35357\/v2.0\/",
          "region": "region-a.geo-1",
          "versionId": "2.0",
          "versionInfo": "https:\/\/region-a.geo-1.identity.hpcloudsvc.com:35357\/v2.0\/",
          "versionList": "https:\/\/region-a.geo-1.identity.hpcloudsvc.com:35357"
        },
        {
          "publicURL": "https:\/\/region-a.geo-1.identity.hpcloudsvc.com:35357\/v3\/",
          "region": "region-a.geo-1",
          "versionId": "3.0",
          "versionInfo": "https:\/\/region-a.geo-1.identity.hpcloudsvc.com:35357\/v3\/",
          "versionList": "https:\/\/region-a.geo-1.identity.hpcloudsvc.com:35357"
        },
        {
          "publicURL": "https:\/\/region-b.geo-1.identity.hpcloudsvc.com:35357\/v2.0\/",
          "region": "region-b.geo-1",
          "versionId": "2.0",
          "versionInfo": "https:\/\/region-b.geo-1.identity.hpcloudsvc.com:35357\/v2.0\/",
          "versionList": "https:\/\/region-b.geo-1.identity.hpcloudsvc.com:35357"
        },
        {
          "publicURL": "https:\/\/region-b.geo-1.identity.hpcloudsvc.com:35357\/v3\/",
          "region": "region-b.geo-1",
          "versionId": "3.0",
          "versionInfo": "https:\/\/region-b.geo-1.identity.hpcloudsvc.com:35357\/v3\/",
          "versionList": "https:\/\/region-b.geo-1.identity.hpcloudsvc.com:35357"
        }
      ]
    },
    {
      "name": "Compute",
      "type": "compute",
      "endpoints": [
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-a.geo-1.compute.hpcloudsvc.com\/v2\/<my-tenant-id>",
          "region": "region-a.geo-1",
          "versionId": "2",
          "versionInfo": "https:\/\/region-a.geo-1.compute.hpcloudsvc.com\/v2\/",
          "versionList": "https:\/\/region-a.geo-1.compute.hpcloudsvc.com"
        },
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-b.geo-1.compute.hpcloudsvc.com\/v2\/<my-tenant-id>",
          "region": "region-b.geo-1",
          "versionId": "2",
          "versionInfo": "https:\/\/region-b.geo-1.compute.hpcloudsvc.com\/v2\/",
          "versionList": "https:\/\/region-b.geo-1.compute.hpcloudsvc.com"
        }
      ]
    },
    {
      "name": "Networking",
      "type": "network",
      "endpoints": [
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-a.geo-1.network.hpcloudsvc.com",
          "publicURL2": "",
          "region": "region-a.geo-1",
          "versionId": "2.0",
          "versionInfo": "https:\/\/region-a.geo-1.network.hpcloudsvc.com",
          "versionList": "https:\/\/region-a.geo-1.network.hpcloudsvc.com"
        },
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-b.geo-1.network.hpcloudsvc.com",
          "publicURL2": "",
          "region": "region-b.geo-1",
          "versionId": "2.0",
          "versionInfo": "https:\/\/region-b.geo-1.network.hpcloudsvc.com",
          "versionList": "https:\/\/region-b.geo-1.network.hpcloudsvc.com"
        }
      ]
    },
    {
      "name": "Usage Reporting",
      "type": "metering",
      "endpoints": [
        {
          "publicURL": "",
          "region": "region-a.geo-1",
          "versionId": "2",
          "versionInfo": "https:\/\/region-a.geo-1.usage-reporting-internal.hpcloudsvc.com:8777",
          "versionList": "https:\/\/region-a.geo-1.usage-reporting-internal.hpcloudsvc.com:8777"
        },
        {
          "publicURL": "",
          "region": "region-b.geo-1",
          "versionId": "2",
          "versionInfo": "https:\/\/region-b.geo-1.usage-reporting-internal.hpcloudsvc.com:8777",
          "versionList": "https:\/\/region-b.geo-1.usage-reporting-internal.hpcloudsvc.com:8777"
        }
      ]
    },
    {
      "name": "Object Storage",
      "type": "object-store",
      "endpoints": [
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-a.geo-1.objects.hpcloudsvc.com\/v1\/<my-tenant-id>",
          "region": "region-a.geo-1",
          "versionId": "1.0",
          "versionInfo": "https:\/\/region-a.geo-1.objects.hpcloudsvc.com\/v1.0\/",
          "versionList": "https:\/\/region-a.geo-1.objects.hpcloudsvc.com"
        },
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-b.geo-1.objects.hpcloudsvc.com\/v1\/<my-tenant-id>",
          "publicURL2": "",
          "region": "region-b.geo-1",
          "versionId": "1",
          "versionInfo": "https:\/\/region-b.geo-1.objects.hpcloudsvc.com\/v1\/",
          "versionList": "https:\/\/region-b.geo-1.objects.hpcloudsvc.com"
        }
      ]
    },
    {
      "name": "Block Storage",
      "type": "volume",
      "endpoints": [
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-a.geo-1.block.hpcloudsvc.com\/v1\/<my-tenant-id>",
          "publicURL2": "",
          "region": "region-a.geo-1",
          "versionId": "1.0",
          "versionInfo": "https:\/\/region-a.geo-1.block.hpcloudsvc.com\/v1",
          "versionList": "https:\/\/region-a.geo-1.block.hpcloudsvc.com"
        },
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-b.geo-1.block.hpcloudsvc.com\/v1\/<my-tenant-id>",
          "publicURL2": "",
          "region": "region-b.geo-1",
          "versionId": "1.0",
          "versionInfo": "https:\/\/region-b.geo-1.block.hpcloudsvc.com\/v1",
          "versionList": "https:\/\/region-b.geo-1.block.hpcloudsvc.com"
        }
      ]
    },
    {
      "name": "CDN",
      "type": "hpext:cdn",
      "endpoints": [
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-a.geo-1.cdnmgmt.hpcloudsvc.com\/v1.0\/<my-tenant-id>",
          "region": "region-a.geo-1",
          "versionId": "1.0",
          "versionInfo": "https:\/\/region-a.geo-1.cdnmgmt.hpcloudsvc.com\/v1.0\/",
          "versionList": "https:\/\/region-a.geo-1.cdnmgmt.hpcloudsvc.com\/"
        },
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-b.geo-1.cdnmgmt.hpcloudsvc.com\/v1.0\/<my-tenant-id>",
          "region": "region-b.geo-1",
          "versionId": "1.0",
          "versionInfo": "https:\/\/region-b.geo-1.cdnmgmt.hpcloudsvc.com\/v1.0\/",
          "versionList": "https:\/\/region-b.geo-1.cdnmgmt.hpcloudsvc.com\/"
        }
      ]
    },
    {
      "name": "Image Management",
      "type": "image",
      "endpoints": [
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-a.geo-1.images.hpcloudsvc.com:443\/v1.0",
          "publicURL2": "",
          "region": "region-a.geo-1",
          "versionId": "1.0",
          "versionInfo": "https:\/\/region-a.geo-1.images.hpcloudsvc.com:443\/v1.0",
          "versionList": "https:\/\/region-a.geo-1.images.hpcloudsvc.com:443"
        },
        {
          "tenantId": "<my-tenant-id>",
          "publicURL": "https:\/\/region-b.geo-1.images.hpcloudsvc.com:443\/v1.0",
          "publicURL2": "",
          "region": "region-b.geo-1",
          "versionId": "1.0",
          "versionInfo": "https:\/\/region-b.geo-1.images.hpcloudsvc.com:443\/v1.0",
          "versionList": "https:\/\/region-b.geo-1.images.hpcloudsvc.com:443"
        }
      ]
    }
  ]
}}
```

**Comment by ywang19** [comment]
The service name should be “Object Storage”, and also, as you defined two regions for the service,
so you’d assign the “region” parameter in <auth> section to designate which region you will access for test as following:

<auth type="keystone" config="username=demo;password=mid;tenant_name=demo;auth_url=http://10.7.190.84:5000/v2.0;service=swift service;region="region-b.geo-1” />


-yaguang

**Comment by gonewest818** [comment]
Thanks, I will give that at try.

Incidentally, I am going to be doing tests against 4 other vendor implementations. 

Another question, is there a way to get more debugging detail on these failures?  For example you asked me for the json output from a successful authentication, and I had to do that y hand with curl.  It seems to me I should be able turn up the verbosity of logging enough to see what communication exists between the drivers and the service. I already have logging level set to DEBUG but there's nothing useful there.

**Comment by gonewest818** [comment]
Setting "region=region-a.geo-1" did work for this particular vendor. Thanks for clarifying.

**Comment by ywang19** [comment]
COSBench consists of two parts, one is controller, another is driver, which has one configuration file, called controller.conf or driver.conf. you can set the log_level parameter as following:
;; this is from controller.conf
[controller]
drivers = 1
log_level = INFO
log_file = log/system.log
archive_dir = archive

;; this is from driver.conf
[driver]
log_level = INFO


-yaguang

**Comment by gonewest818** [comment]
yes, but even with log_level=DEBUG there was nothing logged that helped me with this issue.  As a suggestion, can the logging be more informative? For example for debugging you could log the elements of the json returned from keystone, and log a message to the user that the parameters in the <auth config=“...” />  tag aren’t sufficient to select a single endpoint.
