### ISSUE TITLE
when the workers is up to 50+,testing keystone + radosgw is alway authing fail

### ISSUE THREAD

**Issue by guanglost** [intel-cloud/cosbench#298]
workload log:
is timeout
there are many like :
'''
================================================== stage: s1-normal ==================================================
---------------------------------- mission: M276666DCA5, driver: driver1 ----------------------------------
2016-01-25 09:29:30,013 [INFO] [Log4jLogManager] - will append log to file /opt/cosbench/log/mission/M276666DCA5.log
2016-01-25 09:29:40,249 [ERROR] [AuthAgent] - unable to login
com.intel.cosbench.api.auth.AuthTimeoutException: com.intel.cosbench.client.keystone.KeystoneTimeoutException: java.net.SocketTimeoutException: Read timed out
	at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:112)
	at com.intel.cosbench.driver.agent.AuthAgent.tryLogin(AuthAgent.java:126)
	at com.intel.cosbench.driver.agent.AuthAgent.login(AuthAgent.java:90)
	at com.intel.cosbench.driver.agent.AuthAgent.execute(AuthAgent.java:52)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.intel.cosbench.client.keystone.KeystoneTimeoutException: java.net.SocketTimeoutException: Read timed out
	at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.POST(HttpAuthHandler.java:58)
	at com.intel.cosbench.client.keystone.KeystoneClient.login(KeystoneClient.java:106)
	at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:110)
	... 9 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:111)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:264)
	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:98)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:282)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:216)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:647)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:464)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.POST(HttpAuthHandler.java:56)
	... 11 more

'''
in the keystone log,there is no error output.

**Comment by ywang19** [comment]
you may try to increase the timeout parameter as following:
  <auth type="keystone" config="timeout=300000;username=tester;password=testing;tenant_name=test;auth_url=http://127.0.0.1:5000/v2.0;service=swift service" />

**Comment by guanglost** [comment]
thank you for answering.
After increasing the timeout,the workers can be up to 200.
But when the workers is upper,another error may appear, is not timeout:
```
---------------------------------- mission: MF7CDA4AD55, driver: driver1 ----------------------------------
2016-01-26 15:33:47,018 [INFO] [Log4jLogManager] - will append log to file /opt/cosbench/log/mission/MF7CDA4AD55.log
2016-01-26 15:34:47,262 [ERROR] [AuthAgent] - unable to login
com.intel.cosbench.api.auth.AuthException: com.intel.cosbench.client.keystone.KeystoneServerException: error receiving response from the keystone
	at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:118)
	at com.intel.cosbench.driver.agent.AuthAgent.tryLogin(AuthAgent.java:126)
	at com.intel.cosbench.driver.agent.AuthAgent.login(AuthAgent.java:90)
	at com.intel.cosbench.driver.agent.AuthAgent.execute(AuthAgent.java:52)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intel.cosbench.client.keystone.KeystoneServerException: error receiving response from the keystone
	at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.POST(HttpAuthHandler.java:65)
	at com.intel.cosbench.client.keystone.KeystoneClient.login(KeystoneClient.java:106)
	at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:110)
	... 9 more
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:101)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:282)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:216)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:647)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:464)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.POST(HttpAuthHandler.java:56)
	... 11 more
```
