### ISSUE TITLE
Cosbench 0.4.2 gave SignatureDoesNotMatch error when work against Ceph/Hammer with HAproxy/HTTPs

### ISSUE THREAD

**Issue by jianghaitao** [intel-cloud/cosbench#319]
I've set up a Ceph / Hammer cluster and set up a cluster of radosgw instances fronted by HAProxy. HTTPS was terminated before forward to the civetweb instances for radosgw instances.

Cosbench 0.4.2 run against HTTP front-end of radosgw without any issue. However, if I changed the endpoint to HTTPS front-end, it failed with following error
```
2016-06-14 14:35:34,433 [ERROR] [AbstractOperator] - worker 1 fail to perform operation testbucket-f8ae72b6-2e58-4cbd-a014-05aaa15988831
com.intel.cosbench.api.storage.StorageException: AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: SignatureDoesNotMatch, AWS Error M
essage: null, S3 Extended Request ID: null
        at com.intel.cosbench.api.S3Stor.S3Storage.createContainer(S3Storage.java:146)
        at com.intel.cosbench.driver.operator.Preparer.doInit(Preparer.java:113)
        at com.intel.cosbench.driver.operator.Preparer.operate(Preparer.java:87)
        at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
        at com.intel.cosbench.driver.operator.Initializer.operate(Initializer.java:1)
        at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
        at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
        at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: SignatureDoesNotMatch, AWS Error Message: null, S3 Extended Request ID: 
null
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:644)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:190)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2974)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2945)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:478)
        at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:811)
        at com.intel.cosbench.api.S3Stor.S3Storage.createContainer(S3Storage.java:140)
        ... 13 more
```

Please advise.

Thanks

**Comment by ommoreno** [comment]
Adding the above environment variable doesn't seem to fix the issue.

**Comment by tsg-** [comment]
Does this have anything to do with signature v2 vs v4? 

http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by ywang19** [comment]
"-Dcom.amazonaws.services.s3.enableV4" is exactly the approach to enable V4.

**Comment by ywang19** [comment]
have you added the parameter into driver nodes? I added the parameter into s3stor as default, you could build an new version to get it enabled by default.

**Comment by rikewang** [comment]
I get same problems, how to fix??

**Comment by hrchu** [comment]
V4 signing in old version Ceph rgw is broken. Ref the issue here: http://tracker.ceph.com/issues/18965

**Comment by bissenbay** [comment]
I have the same issue. How to solve?

**Comment by ghisl1** [comment]
Hi,
it seems that to run properly, SSL terminaison might be at Rados Gateway side.
I have the same problem and will try to solve it asap

**Comment by woshizhicainiaoluguo** [comment]
same problem ,any advice?
"-Dcom.amazonaws.services.s3.enableV4" seems doesn't work.
ceph v14.2.3
cosbench 0.4.2.c4
need your help
@ywang19 
@hrchu 
@ghisl1 
@tsg-

**Comment by woshizhicainiaoluguo** [comment]
by the way ,how did you resolve it ...
@jianghaitao 
thank you
