### ISSUE TITLE
cosbench runs into ArrayIndexOutOfBoundsException on both 0.4.2.c3 and 0.4.2.c4

### ISSUE THREAD

**Issue by atheism** [intel-cloud/cosbench#323]
When ran ceph s3 tests against our own server. we got the following error in system.log.
2016-07-04 09:51:32,568 [ERROR] [AbstractAgent] - unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.intel.cosbench.driver.operator.AbstractOperator.errorStatisticsHandle(AbstractOperator.java:117)
        at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:103)
        at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
        at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
        at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
        at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
        at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-07-04 09:51:32,573 [ERROR] [AbstractAgent] - unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.intel.cosbench.driver.operator.AbstractOperator.errorStatisticsHandle(AbstractOperator.java:117)
        at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:103)
        at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
        at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
        at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
        at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
        at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

We have written 5000 objects in each bucket. and when we test 100 percent random read to a bucket, the problem occurs and the test is terminated.
The config file used in this test:
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="ceph-s3-test-read-1bucket-32worker" description="random 50k-150K files sample benchmark for ceph s3">

    <storage type="s3" config="accesskey=ACCESSKEY;secretkey=SECRETKEY;proxyhost=;proxyport=;endpoint=http://192.168.1.182" />

  <workflow>

    <workstage name="main">
      <work name="main" workers="32" runtime="100">
        <operation type="read" ratio="100" config="cprefix=s3testclone1;containers=u(1,1);objects=u(1,5000)" />
      </work>
    </workstage>

  </workflow>

</workload>

**Comment by qiujianzhong** [comment]
Maybe  AK/SK  was wrong.
