### ISSUE TITLE
Does cosbench support keystone v3 auth?

### ISSUE THREAD

**Issue by santaclause88** [intel-cloud/cosbench#330]
Hello,

I am trying to use cosbench with keystone v3.  Is this currently supported on cosbench?

This is my config:
<auth type="keystone" config="username=admin;password=passw0rd;tenant_name=admin;auth_url=http://172.29.236.50:5000/v3;service=swift;retry=10"/>

This is what I see in the driver log
I know the user name and pass is right because that is what is in the openrc

2016-08-25 20:09:58,016 [ERROR] [AuthAgent] - bad username and password
com.intel.cosbench.api.auth.AuthBadException: com.intel.cosbench.client.keystone.KeystoneAuthException
	at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:116)
	at com.intel.cosbench.driver.agent.AuthAgent.tryLogin(AuthAgent.java:126)
	at com.intel.cosbench.driver.agent.AuthAgent.login(AuthAgent.java:81)
	at com.intel.cosbench.driver.agent.AuthAgent.execute(AuthAgent.java:52)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intel.cosbench.client.keystone.KeystoneAuthException
	at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.parseResponse(HttpAuthHandler.java:88)
	at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.POST(HttpAuthHandler.java:67)
	at com.intel.cosbench.client.keystone.KeystoneClient.login(KeystoneClient.java:106)
	at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:110)
	... 9 more

**Comment by ywang19** [comment]
Yes, v3 is supported, pls make sure you set region parameter.


在 2016年8月26日，上午9:17，santaclause88 <notifications@github.com> 写道：

Hello,

I am trying to use cosbench with keystone v3. Is this currently supported on cosbench?

This is my config:
This is what I see in the driver log
I know the user name and pass is right because that is what is in the openrc

2016-08-25 20:09:58,016 [ERROR] [AuthAgent] - bad username and password
com.intel.cosbench.api.auth.AuthBadException: com.intel.cosbench.client.keystone.KeystoneAuthException
at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:116)
at com.intel.cosbench.driver.agent.AuthAgent.tryLogin(AuthAgent.java:126)
at com.intel.cosbench.driver.agent.AuthAgent.login(AuthAgent.java:81)
at com.intel.cosbench.driver.agent.AuthAgent.execute(AuthAgent.java:52)
at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.intel.cosbench.client.keystone.KeystoneAuthException
at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.parseResponse(HttpAuthHandler.java:88)
at com.intel.cosbench.client.keystone.handler.HttpAuthHandler.POST(HttpAuthHandler.java:67)
at com.intel.cosbench.client.keystone.KeystoneClient.login(KeystoneClient.java:106)
at com.intel.cosbench.api.keystone.KeystoneAuth.login(KeystoneAuth.java:110)
... 9 more

**Comment by santaclause88** [comment]
Hi

I have set the region parameter and am still seeing the same issue. 

I cannot seem to find how to change the log level for the drivers. I did set the controller to debug but how do I do so for the drivers?

This is my new auth

> <auth type="keystone" config="username=swift;password=swift;tenant_name=service;auth_url=http://172.29.236.50:5000/v3;service=swift;retry=10;region=regionOne"/>

**Comment by ywang19** [comment]
to change log level for driver, you need create a driver.conf on driver nodes.


在 2016年8月26日，下午11:52，santaclause88 <notifications@github.com> 写道：

Hi

I have set the region parameter and am still seeing the same issue.

I cannot seem to find how to change the log level for the drivers. I did set the controller to debug but how do I do so for the drivers?

This is my new auth

**Comment by cb371j** [comment]
Did you ever get cosbench to work with keystone v3?

**Comment by ywang19** [comment]
yes, keystone v3 is supported.



yago.wang@gmail.com
 
From: cb371j
Date: 2017-02-03 04:58
To: intel-cloud/cosbench
CC: ywang; Comment
Subject: Re: [intel-cloud/cosbench] Does cosbench support keystone v3 auth for swift? (#330)
Did you ever get cosbench to work with keystone v3?

**Comment by f0o** [comment]
@ywang19 how?
I am at the same issue..

**Comment by f0o** [comment]
It looks to me like cosbench tries to talk v2 auth json to the v3 URL which obviously fails.

How can it tell cosbench to truly use v3?

**Comment by zhoubofsy** [comment]
same issue

**Comment by sdu-merrye** [comment]
same issue

**Comment by mujtabainamdar** [comment]
> It looks to me like cosbench tries to talk v2 auth json to the v3 URL which obviously fails.
> 
> How can it tell cosbench to truly use v3?

Any luck in getting this to work ?

**Comment by f0o** [comment]
Nope, I just gave it up

**Comment by mujtabainamdar** [comment]
> Nope, I just gave it up

Me too

**Comment by osmboy** [comment]
Hi guys!  keystone v3 is supported by this branch [keystoneV3](https://github.com/OStorage/cosbench/tree/keystoneV3), you can pull this source code and build it by eclipse, the details please refer to BUILD.md, or just download the jar [cosbench-keystone_0.4.2.0.jar.zip](https://github.com/intel-cloud/cosbench/files/7452335/cosbench-keystone_0.4.2.0.jar.zip) to use.
here is the keystoneV3 example config:
```yaml
<auth type="keystone" config="username=tester;tenant_name=test;password=testing;domain=default;url=http://127.0.0.1:5000/v3;service=swift;retry=10"/>
```
it works well in my keystoneV3 env
![image](https://user-images.githubusercontent.com/20849756/136041209-bfe03691-5924-486b-b3c5-5e5d31b467c9.png)
For follow-up questions, you can submit an issue to this [repo](https://github.com/OStorage/cosbench/tree/keystoneV3).
the pull request is #421

**Comment by digvijay2040** [comment]
Hi, Added improvement to @osmboy repo,  Added support for passing project_domain id and user_domain_id from config file

you can use this branch [keystoneV3Support](https://github.com/digvijay2040/cosbench/tree/keystoneV3Support) . Please refer to BUILD.md to build it using eclipse. Please download eclipse for rcp and rap developers if you don't get options mentioned in BUILD.md or you can download already build jar file [cosbench-keystone_0.4.2.0.jar](https://git.voereir.io/voereir/cosbenchv3/-/blob/0.4.2/osgi/plugins/cosbench-keystone_0.4.2.0.jar) . Move this jar file to your cosbench release 0.4.2.0  osgi/plugins/ folder.

here is the updated keystoneV3 config:
```<auth type="keystone" config="username={{USERNAME}};password={{PASSWORD}};project_domain={{PROJECT_DOMAIN_ID}};user_domain={{USER_DOMAIN_ID}};tenant_name={{TENANT_NAME}};auth_url={{AUTH_URL}};service=swift;retry=5"/>```
update params according to your openrc.

for any question you can submit an issue to this [repo](https://github.com/digvijay2040/cosbench/tree/keystoneV3Support)
to check the changes Pull request is [#428 ](https://github.com/intel-cloud/cosbench/pull/428)

I used
```OS: macos 
Eclipse IDE for RCP and RAP Developers (includes Incubating components)
Version: 2022-06 (4.24.0)
Build id: 20220609-1112```

**Comment by sulaimanyu** [comment]
Hi, there
my swift v3 auth information did not have tenant_id and tenant_name, and I use project_id and project_name to do the auth. how can I pass project_id and project_name to cosbench auth config?
Thanks
