### ISSUE TITLE
cosbench - [ERROR] java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by hoky5611** [intel-cloud/cosbench#331]
cosbench version - 0.4.2
ceph jewel version - 10.2.2

It is possible to measure normally write. In the case of 4KB read/128KB worker 20-40 ... Increases, terminated.

Log analysis java.lang.ArrayIndexOutOfBoundsException: 0
It is possible to measure normally write.
Read why terminated?

**Let us know in detail how to solve**

 log ------------------------------------------------------------------------------------------------------------
2016-09-02 09:16:34,815 [ERROR] [AbstractAgent] - unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.intel.cosbench.driver.operator.AbstractOperator.errorStatisticsHandle(AbstractOperator.java:117)
        at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:103)
        at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
        at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
        at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
        at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
        at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745) 
---------------------------------------------------------------------------------------------------------------

**Comment by hoky5611** [comment]
#323

**Comment by hoky5611** [comment]
COSBench 0.3.3.0 (13-ww44.5)
------------------------------------
. #20: multiple same operations
. #16: web console authentication
. #34: 0% success on write
. #11: job management
. #70: multiple main stages
. #30: no historical workloads after restart
. add histogram selector to define histogram size distribution
. #58: sleep between stage
. #84: multiple init/prepare/cleanup/dispose from config UI
. **oen bug fix for java.lang.ArrayIndexOutOfBoundsException at data archiving**
. #118: file-write operation - percentile zero issue
. #121: specify archive dir
. #92: using swift storage without authentication
. support auth token caching for swift testing
. #128: Use workstage name from XML rather than generic names in logs

https://github.com/intel-cloud/cosbench/blob/308db3c2cf5d5decec213fdd98593c589f3130dd/CHANGELOG

**Comment by ericychoi** [comment]
+1 here, anyone have any insight?

**Comment by IvanJobs** [comment]
+1 I met the same issue just today after a few rounds of tests.

**Comment by Wilhelmshaven** [comment]
Using `radosgw-admin bucket stats –bucket=bucketName` to check whether you have upload full data. When using a large number of workers, COSBench can't PUT all data to ceph, although COSBench tells you that successful rate is 100%. In such cases, read will be terminated.

**Comment by ShreyasC** [comment]
I face the same issue too

**Comment by akumacxd** [comment]
I met the same issue, version 0.4.2
2017-08-11 15:17:13,707 [ERROR] [AbstractAgent] - unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.intel.cosbench.driver.operator.AbstractOperator.errorStatisticsHandle(AbstractOperator.java:117)
	at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:103)
	at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
	at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
	at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
	at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
	at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by fifthpostulate** [comment]
Experiencing the same issue with version 0.4.2 as well:
2018-05-10 11:52:45,653 [ERROR] [AbstractAgent] - unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.intel.cosbench.driver.operator.AbstractOperator.errorStatisticsHandle(AbstractOperator.java:117)
        at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:103)
        at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
        at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
        at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
        at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
        at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)

**Comment by Tanyy** [comment]
and anyone fixed that or solved that?

**Comment by cryptarchnoble** [comment]
Also experiencing this issue. The odd thing for me is, it only happens when performing S3 read operations with a high number of workers (200+ per host workload server). Below this number, everything works just fine... and if doing writes, it also works fine. I can also get 500+ workers when using other protocols (swift).
