### ISSUE TITLE
worker fail to perform operation

### ISSUE THREAD

**Issue by benamuk** [intel-cloud/cosbench#362]
Test ran with the prefix costest1 to costest3. After that, when using costest4 and above I get the attached error and I can’t explain where that comes from.

================================================== stage: s1-init ==================================================
---------------------------------- mission: MFCE343FFD8, driver: driver1 ----------------------------------
2017-09-29 08:14:44,007 [INFO] [Log4jLogManager] - will append log to file /root/0.4.2.c4/log/mission/MFCE343FFD8.log
2017-09-29 08:14:44,218 [INFO] [NoneStorage] - performing PUT at /costest51
2017-09-29 08:15:14,568 [ERROR] [AbstractOperator] - worker 1 fail to perform operation costest51
com.intel.cosbench.api.storage.StorageException: com.amazonaws.services.s3.model.AmazonS3Exception: Your previous request to create the named bucket succeeded and you already own it. (Service: Amazon S3; Status Code: 409; Error Code: BucketAlreadyOwnedByYou; Request ID: 88e1c1d8-77f1-48ac-b7c1-e95c68fce403), S3 Extended Request ID: null
	at com.intel.cosbench.api.S3Stor.S3Storage.createContainer(S3Storage.java:149)
	at com.intel.cosbench.driver.operator.Preparer.doInit(Preparer.java:113)
	at com.intel.cosbench.driver.operator.Preparer.operate(Preparer.java:87)
	at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
	at com.intel.cosbench.driver.operator.Initializer.operate(Initializer.java:1)
	at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
	at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
	at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Your previous request to create the named bucket succeeded and you already own it. (Service: Amazon S3; Status Code: 409; Error Code: BucketAlreadyOwnedByYou; Request ID: 88e1c1d8-77f1-48ac-b7c1-e95c68fce403), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:796)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:732)
	at com.intel.cosbench.api.S3Stor.S3Storage.createContainer(S3Storage.java:145)
	... 13 more
================================================== stage: s2-client-write-1M ==================================================
================================================== stage: s3-client1-read-1M ==================================================
================================================== stage: s4-cleanup-128workers ==================================================
================================================== stage: s5-dispose-1worker ==================================================

Workload.xml file used.

<?xml version="1.0" encoding="UTF-8" ?>
<workload name="Cf-1MB-128" description="workload configuration">

  <storage type="s3" config="accesskey=lGCan8V8BHPkKhSYedrR;secretkey=PsW9jMzY5pBkhYRFKgiz29VsKH2joLVApG8bZMWz;endpoint=http://192.168.1.101" />
  
  <workflow>
    
    <workstage name="init">
      <work type="init" workers="1" config="cprefix=costest1;containers=r(1,20)" id="op1" />
    </workstage>
	
    <workstage name="client-write-1M" closuredelay="30" config="">
      <work name="client1" type="normal" workers="128" interval="5" division="none" runtime="300" rampup="0" rampdown="0" afr="0" totalOps="10000" totalBytes="0" driver="driver1">
        <storage type="s3" config="accesskey=lGCan8V8BHPkKhSYedrR;secretkey=PsW9jMzY5pBkhYRFKgiz29VsKH2joLVApG8bZMWz;endpoint=http://192.168.1.101" />
		<operation type="write" ratio="100" chunked="True" division="none" config="cprefix=costest1;containers=r(1,10);objects=r(1,50000);sizes=c(1)MB" id="op2"/>
      </work>
	  <work name="client2" type="normal" workers="128" interval="5" division="none" runtime="300" rampup="0" rampdown="0" afr="0" totalOps="10000" totalBytes="0" driver="driver2">
        <storage type="s3" config="accesskey=lGCan8V8BHPkKhSYedrR;secretkey=PsW9jMzY5pBkhYRFKgiz29VsKH2joLVApG8bZMWz;endpoint=http://192.168.1.101" />
		<operation type="write" ratio="100" chunked="True" division="none" config="cprefix=costest1;containers=r(11,20);objects=r(1,50000);sizes=c(1)MB" id="op3"/>
      </work>
    </workstage>
	
    <workstage name="client1-read-1M" closuredelay="30" config="">
      <work name="client1" type="normal" workers="128" interval="5" division="none" runtime="300" rampup="0" rampdown="0" afr="0" totalOps="10000" totalBytes="0" driver="driver1">
	    <storage type="s3" config="accesskey=lGCan8V8BHPkKhSYedrR;secretkey=PsW9jMzY5pBkhYRFKgiz29VsKH2joLVApG8bZMWz;endpoint=http://192.168.1.101" />
        <operation type="read" ratio="100" chunked="True" division="none" config="cprefix=costest1;containers=r(1,10);objects=r(1,50000)" id="op4"/>
      </work>
	  <work name="client2" type="normal" workers="128" interval="5" division="none" runtime="300" rampup="0" rampdown="0" afr="0" totalOps="10000" totalBytes="0" driver="driver2">
	    <storage type="s3" config="accesskey=lGCan8V8BHPkKhSYedrR;secretkey=PsW9jMzY5pBkhYRFKgiz29VsKH2joLVApG8bZMWz;endpoint=http://192.168.1.101" />
        <operation type="read" ratio="100" chunked="True" division="none" config="cprefix=costest1;containers=r(11,20);objects=r(1,50000)" id="op5"/>
      </work>
    </workstage>
    
	<workstage name="cleanup-128workers" closuredelay="30">
      <work type="cleanup" workers="128" config="cprefix=costest1;containers=r(1,20);objects=r(1,50000)" id="op6"/>
    </workstage>
	
	<workstage name="dispose-1worker" closuredelay="30">
      <work type="dispose" workers="16" config="cprefix=costest1;containers=r(1,20)" id="op7"/>
    </workstage>
      
  </workflow>
  
</workload>

Any recommendations on the errors received please?

Thank you.

**Comment by bissenbay** [comment]
Does anyone figure out what was the problem?
