### ISSUE TITLE
Error: Could not find or load main class org.eclipse.equinox.launcher.Main

### ISSUE THREAD

**Issue by karynhuang55** [intel-cloud/cosbench#386]
Hi :
It doesn't work version 0.4.2，How can i solve this problem?

# cat log/controller-boot.log   
Error: Could not find or load main class org.eclipse.equinox.launcher.Main  

# sh start-all.sh   
cat: VERSION: No such file or directory  
Launching osgi framwork ...   
Successfully launched osgi framework!  
Booting cosbench driver ...   
Ncat: Connection refused.  
.Ncat: Connection refused.  
.Ncat: Connection refused.  
.Ncat: Connection refused.  
.Ncat: Connection refused.

**Comment by samuelsh** [comment]
Reproduced with 0.4.2 on CentOS 7

```bash
[vastdata@cc3n3 cos]$ bash -x ./cosbench-start.sh
+ SERVICE_NAME=
+ BOOT_LOG=log/-boot.log
+ OSGI_BUNDLES=
+ OSGI_CONSOLE_PORT=
+ OSGI_CONFIG=conf/.
+ TOMCAT_CONFIG=conf/-tomcat-server.xml
+ TOOL=nc
+ TOOL_PARAMS='-i 5m'
+ rm -f log/-boot.log
+ mkdir -p log
+ echo 'Launching osgi framwork ... '
Launching osgi framwork ...
+ '[' 0 -ne 0 ']'
+ sleep 1
+ /usr/bin/nohup java -Dcosbench.tomcat.config=conf/-tomcat-server.xml -server -cp main/org.eclipse.equinox.launcher_1.2.0.v20110502.jar org.eclipse.equinox.launcher.Main -configuration conf/. -console
+ echo 'Successfully launched osgi framework!'
Successfully launched osgi framework!
+ echo 'Booting cosbench  ... '
Booting cosbench  ...
+ succ=1
+ which nc
+ '[' 0 -ne 0 ']'
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 1 ']'
+ echo 'Successfully started cosbench !'
Successfully started cosbench !
+ cat log/-boot.log
An error has occurred.  See the log file
/qa/0.4.2/conf/./1544033636419.log
+ exit 0

$ cat /qa/0.4.2/conf/./1544033636419.log
!SESSION Wed Dec 05 18:13:56 GMT 2018 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2018-12-05 18:13:56.435
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.RuntimeException: Could not find framework
        at org.eclipse.equinox.launcher.Main.getBootPath(Main.java:978)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:557)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
```

**Comment by bissenbay** [comment]
I have the same issue. Does anybody solve it?

**Comment by samuelsh** [comment]
0.4.2 Release seems to be broken.
Follow this link, to see how to fix and rebuild Cosbench project:
https://github.com/ekaynar/Benchmarks/blob/master/cosbench/BUILD.MD

**Comment by ksingh7** [comment]
+1 

0.4.2 release is broken

![image](https://user-images.githubusercontent.com/9701902/60349469-48d22880-99df-11e9-9eac-c05dbd6030b8.png)

**Comment by acoooder** [comment]
cat: VERSION: No such file or directory

you should exec "sh pack.sh verisonid" at first,then a directory named versionid maked.enter this directory run start-all.sh

**Comment by cvicente22** [comment]
can help on this. I've installed cosbench but when running it keeps on freezing on booting cosbench driver. when i check the logs below is the result

![cosbench](https://user-images.githubusercontent.com/56626862/71968349-b0dfb200-323f-11ea-9c6f-67a608cb6aa6.JPG)

**Comment by bakingclouds6x** [comment]
Got same error. Any fix or still unresolved?

**Comment by nzncngz** [comment]
I get the same problem. Any suggestions with the problem?
