### ISSUE TITLE
Why Write workload is OK, but always failed read workload?

### ISSUE THREAD

**Issue by coollinn** [intel-cloud/cosbench#387]
Hi Sir,

I just test s3 storage with cosbench 0.4.2rc4 in RHLE7.4, the s3 connect was working and write workload can processing normally.
But why the read workload always failed with following error:

2018-08-18 16:44:37,277 [ERROR] [AbstractOperator] - worker 1 fail to perform operation s3testqwer1/myobjects2
java.lang.NullPointerException
        at com.intel.cosbench.driver.operator.Reader.copyLarge(Reader.java:120)
        at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:92)
        at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
        at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
        at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
        at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
        at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
        at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

the config:
more access-s3-workload.conf
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="s3-sample" description="sample benchmark for s3">

  <storage type="s3" config="accesskey=ODlmYjE2NTAxOWI4MmE;secretkey=NzlmYzVjOWFiYzg1M2Q4MTA3ZDBhZjRlNDYxZTh;endpoint=http://s3.va732:8143/co
sbench;path_style_access=true" />

  <workflow>

    <workstage name="init">
      <work type="init" workers="1" config="cprefix=s3testqwer;containers=r(1,2)" />
    </workstage>

    <workstage name="prepare">
      <work type="prepare" workers="1" config="cprefix=s3testqwer;containers=r(1,2);objects=r(1,10);sizes=c(64)KB;hashCheck=false" />
    </workstage>

    <workstage name="main">
      <work name="main" workers="8" runtime="60">
        <operation type="read" ratio="80" config="cprefix=s3testqwer;containers=u(1,2);objects=u(1,10);hashCheck=false" />
        <operation type="write" ratio="20" config="cprefix=s3testqwer;containers=u(1,2);objects=u(11,20);sizes=c(64)KB;hashCheck=false" />
      </work>
    </workstage>

    <workstage name="cleanup">
      <work type="cleanup" workers="1" config="cprefix=s3testqwer;containers=r(1,2);objects=r(1,20)" />
    </workstage>

    <workstage name="dispose">
      <work type="dispose" workers="1" config="cprefix=s3testqwer;containers=r(1,2)" />
    </workstage>
  </workflow>

</workload>

**Comment by rrichardson** [comment]
I have the same problem.  Using Minio as the target Object Storage

**Comment by lilingzj** [comment]
I have the same problem. How to solve this problem？

**Comment by wgy855** [comment]
Same here. Does any one have solution?

**Comment by wancoso** [comment]
I have the same problem. Is there a solution?
