### ISSUE TITLE
[ERROR] [AbstractAgent] - StringIndexOutOfBoundsException: String index out of range: 12

### ISSUE THREAD

**Issue by xieyuyang** [intel-cloud/cosbench#399]
cosbench version - 0.4.2.c4

read 4G file use 64 workers: 

 \<work type="prepare" workers="1" config="cprefix=bucket;containers=r(1,1);objects=r(1,1);sizes=c(4)GB" />
\<workstage name="read-object">
      \<work name="main" workers="64" runtime="20">
        \<operation type="read" ratio="100" config="cprefix=bucket;containers=u(1,1);objects=u(1,1)" />
      \</work>
\</workstage>

Cosbench may keep processing, check logs, find this:

2020-07-06 13:52:11,406 [ERROR] [AbstractAgent] - unexpected exception
java.lang.StringIndexOutOfBoundsException: String index out of range: 12
    at java.lang.String.substring(String.java:1963)
    at com.intel.cosbench.driver.operator.AbstractOperator.isUnauthorizedException(AbstractOperator.java:134)
    at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:102)
    at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
    at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
    at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
    at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
    at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
    at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
    at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)

**Comment by xuzhiwan** [comment]
I also encountered this problem, can you tell me how to solve it?

**Comment by xuzhiwan** [comment]
I also met this problem, could you tell me how to solve it, thank you！
